config/routes.rb
Rails.application.routes.draw do
  get 'games/new', to: 'games#new', as: 'new_game'
  post 'games/score', to: 'games#score', as: 'score_game'

  # Define root path
  root "games#new"

  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'open-uri'

class GamesController < ApplicationController
  def new
    @letters = Array.new(10) { ('A'..'Z').to_a.sample }
  end

  def score
    @letters = params[:letters].split
    @word = params[:word]
    @result = run_game(@word, @letters)

    # Update the session score
    session[:score] ||= 0
    if @result.start_with?("Congratulations")
      session[:score] += @word.length
    end
  end

  private

  def run_game(word, grid)
    if valid_word?(word) && word_in_grid?(word, grid)
      "Congratulations! #{word} is a valid English word and can be built from the grid."
    elsif !word_in_grid?(word, grid)
      "Sorry, but #{word} can't be built out of the grid."
    else
      "Sorry, but #{word} is not a valid English word."
    end
  end

  def word_in_grid?(word, grid)
    word.upcase.chars.all? { |letter| word.upcase.count(letter) <= grid.count(letter) }
  end

  def valid_word?(word)
    url = "https://wagon-dictionary.herokuapp.com/#{word}"
    response = URI.open(url).read
    json = JSON.parse(response)
    json['found']
  rescue OpenURI::HTTPError
    false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Longest Word Game</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <h1 class="text-center my-4">Longest Word Game</h1>
      <div class="text-center">
        <h3>Letters Grid</h3>
        <ul class="list-inline">
          <% @letters.each do |letter| %>
            <li class="list-inline-item border rounded p-2"><%= letter %></li>
          <% end %>
        </ul>
        <%= form_with url: score_game_path, method: :post, local: true, class: "mt-4" do |form| %>
          <%= hidden_field_tag :letters, @letters.join(" ") %>
          <div class="form-group">
            <%= form.label :word, "Enter a word:" %>
            <%= form.text_field :word, class: "form-control" %>
          </div>
          <%= form.submit "Submit", class: "btn btn-primary mt-2" %>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/games/score.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Longest Word Game</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <h1 class="text-center my-4">Game Results</h1>
      <p class="text-center"><%= @result %></p>
      <div class="text-center mt-4">
        <h4>Current Score: <%= session[:score] || 0 %></h4>
        <%= link_to "Play Again", new_game_path, class: "btn btn-outline-primary" %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>